language: node_js
node_js:
- 6
- 4
- 0.10
services:
- rabbitmq
- mysql
- redis-server
before_install:
- mysql -e "create database IF NOT EXISTS \`lock\`;" -uroot
script:
- npm run typings
- npm run build -- --declaration
- npm test
after_success:
- test $TRAVIS_NODE_VERSION = "6" && npm run coverage
deploy:
  provider: npm
  api_key:
    secure: Xs+reBaG7JLUqhVLofg/P2spdb4B5HcwCsQKpO1EXjuyjP42X006C1InJ5tf7YUggC249wqHcA8743dkb3hpShcR7Ebtqdff+GqVqzxCjYitFOjfaDRCy9rcvzYYmtwLhmUN2C4cML6fucI/sJ4ecrnd8pRxDuG8YAoqIvh0arf+h+n7rROxpdbVDTNwMVWqToVydl1V7bP4B6TPFd0cM4vu1EbGBwuqpC9CdXJ9F9M6Jqkj98v93UiyqQD5MQdO1AXqdf7rS1ICXGAAVuQTgiGS/i8zIf/AneTaGp29VMbHyQhNIfTb2kqR30PLVtTpfMk76E7r1T9G9phYuA0EDqI1t5D4pjYmBiO1XeXva3m03/mZHgqMZptOVVtQIlzapX8N1XGP/kd/v+JfeDMfkBXKOsHaMz7jbYhJdxRM8wbdIYaSsa1BwHef2LxL1qq9m2Ixtsqt0EfteMw5BWn/wXaGBGIZdJNftE+HU819LPHbXsIHB4WlhCOoRkmQjWab8Tlh6v3nZrrUlsSQYtxJkMKMDgvBCYHTUPGlHQXuYgiRbvN23s4OX6AO3ZTpI1sarq/bGg7YK6os7uSV5mNNPoU0MYCOWlOuVtu3E5tIYeUXit+r8P9iLwQLBekaV7Vro+zGiln1opBDIGtq1XrYZzJZNCqnC85HRiDC+qstENY=
  email:
    secure: guJHcegwbeu9KO8r1boA9IuOkMQkO2qM/O137sKgopBHjMiFfgx0JXuFzUUEZiSbNvN5gwgUEGBgKMwTTF3S+IKHGNoAKp48LPWvoTOc4irWQHct1WTuCgMxe99bZw1JFN9mzbeEJxOTcGSZTZ8zUUZ9/dYzuKLNn+iCdXspLySiF0DDo+t5JrtYHWsTviO7EYljR3jNtENvC/8XA08cTmAY+P23mCsktAlIZkEDtkPPPIT2mxEJd3610uBzbmpu32RuzUKN4MpqXRJX6IJEGCAI7dbrFk/Ia0TMI35ICMJ72kAg+XpTC0ve3JJkq+3DVfD/TKo3L38U4vctl/RB7Rhnf2m+w/Z8JGVV1bk7MBYeL0gaz2RM7NfpANh7N1jSIUSzr9Qrgu+xq4WEgPijsyoVmjIotyCuGkBptFInCkkqCrJ/3GkE8hh6JSyxxSeALlgmeoXu5fpvKEZ4cut/x/mKCbIndXy5wLk9ev0BZkLooBWaxYYeY0faZ0dM9AyJ/HjyrDWN2AeqmRiXXoZRvha8mEoTYnWxLNdUVnMMI/UZBDLJquAYfZumiQcM5uTKLtHmEUfMd1LvJEWRzQgVUS1rxpr+mOJzPEwEyD7vmbbp0dBv4lbCrGceoQike+Z83BzQCuNCh7wE1Oa9SKpKRnAGCEZ/xJuL8dCzb5cYeZ4=
  on:
    node: 6
    tags: true
    repo: urbanmassage/node-range-lock
  skip_cleanup: true
